import ExcelJS from 'exceljs';
import { prisma } from '../../../../lib/prisma';
import { currentUser } from '../../../../lib/auth';
function minToText(m){const h=Math.floor((m||0)/60),mm=(m||0)%60;return `${h}h ${mm}m`}
export async function GET(){
 const user=currentUser(); if(!user||user.role!=='ADMIN')return Response.json({error:'Forbidden'},{status:403});
 const companies=await prisma.company.findMany({include:{workEntries:true,extraOrders:true,assignedUser:true},orderBy:{name:'asc'}});
 const entries=await prisma.workEntry.findMany({include:{company:true,user:true},orderBy:{date:'desc'}});
 const orders=await prisma.extraOrder.findMany({include:{company:true},orderBy:{date:'desc'}});
 const wb=new ExcelJS.Workbook(); wb.creator='Safety Service';
 const s=wb.addWorksheet('Podsumowanie');
 s.columns=[{header:'Firma',key:'name',width:30},{header:'Pracownik',key:'employee',width:24},{header:'Godziny',key:'hours',width:16},{header:'Dojazdy',key:'travel',width:16},{header:'Kwota miesięczna',key:'monthly',width:18},{header:'Zlecenia dodatkowe',key:'orders',width:20},{header:'Koszty',key:'costs',width:16},{header:'Zysk',key:'profit',width:16},{header:'Stawka/h',key:'rate',width:16},{header:'Rentowność',key:'rent',width:16}];
 companies.forEach(c=>{const workMinutes=c.workEntries.reduce((sum,e)=>sum+e.minutes,0);const orderMinutes=c.extraOrders.reduce((sum,o)=>sum+Number(o.minutes||0),0);const minutes=workMinutes+orderMinutes;const travel=c.workEntries.reduce((sum,e)=>sum+(e.travelMinutes||0),0);const monthly=Number(c.netAmount||0);const ordersNet=c.extraOrders.reduce((sum,o)=>sum+Number(o.netAmount||0),0);const entryCosts=c.workEntries.reduce((sum,e)=>sum+Number(e.additionalCost||0),0);const orderCosts=c.extraOrders.reduce((sum,o)=>sum+Number(o.travelCost||0)+Number(o.extraCost||0),0);const costs=Number(c.travelCost||0)+Number(c.extraCost||0)+entryCosts+orderCosts;const timeCost=(minutes/60)*120;const profit=monthly+ordersNet-costs-timeCost;const rate=minutes?profit/(minutes/60):0;const rent=profit>0?(rate>=250?'Wysoka':'Średnia'):(minutes||costs||monthly||ordersNet)?'Niska':'Brak';s.addRow({name:c.name,employee:c.assignedUser?.name||'',hours:minToText(minutes),travel:minToText(travel),monthly,orders:ordersNet,costs,profit:+profit.toFixed(2),rate:+rate.toFixed(2),rent})});
 s.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};s.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF132734'}};s.autoFilter='A1:J1';
 const h=wb.addWorksheet('Historia pracy');
 h.columns=[{header:'Data',key:'date',width:16},{header:'Firma',key:'company',width:30},{header:'Użytkownik',key:'user',width:22},{header:'Czynność',key:'title',width:24},{header:'Opis',key:'description',width:50},{header:'Czas pracy',key:'time',width:14},{header:'Dojazd',key:'travel',width:14},{header:'Koszt dodatkowy',key:'additionalCost',width:18},{header:'Opis kosztu',key:'additionalCostDescription',width:30}];
 entries.forEach(e=>h.addRow({date:e.date.toISOString().slice(0,10),company:e.company.name,user:e.user.name,title:e.title,description:e.description,time:minToText(e.minutes),travel:minToText(e.travelMinutes||0),additionalCost:Number(e.additionalCost||0),additionalCostDescription:e.additionalCostDescription||''}));
 h.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};h.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFF5A14'}};h.autoFilter='A1:I1';
 const z=wb.addWorksheet('Zlecenia dodatkowe');
 z.columns=[{header:'Data',key:'date',width:16},{header:'Firma',key:'company',width:30},{header:'Nazwa',key:'title',width:30},{header:'Typ',key:'type',width:24},{header:'Czas poświęcony',key:'time',width:18},{header:'Opis',key:'description',width:40},{header:'Kwota netto',key:'net',width:16},{header:'Koszt dojazdów',key:'travelCost',width:16},{header:'Dodatkowe koszty',key:'extraCost',width:18},{header:'Koszt czasu',key:'timeCost',width:16},{header:'Opis kosztów',key:'extraCostDescription',width:30},{header:'Zysk',key:'profit',width:16},{header:'Status',key:'status',width:16}];
 orders.forEach(o=>{const timeCost=(Number(o.minutes||0)/60)*120;z.addRow({date:o.date.toISOString().slice(0,10),company:o.company.name,title:o.title,type:o.type,time:minToText(Number(o.minutes||0)),description:o.description||'',net:Number(o.netAmount||0),travelCost:Number(o.travelCost||0),extraCost:Number(o.extraCost||0),timeCost:+timeCost.toFixed(2),extraCostDescription:o.extraCostDescription||'',profit:+(Number(o.netAmount||0)-Number(o.travelCost||0)-Number(o.extraCost||0)-timeCost).toFixed(2),status:o.status})});
 z.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};z.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF132734'}};z.autoFilter='A1:M1';
 const st=wb.addWorksheet('Statystyki');st.addRows([['Statystyka','Wartość'],['Liczba firm',companies.length],['Liczba wpisów',entries.length],['Liczba zleceń dodatkowych',orders.length],['Suma godzin',entries.reduce((x,e)=>x+e.minutes,0)/60],['Suma dojazdów',entries.reduce((x,e)=>x+(e.travelMinutes||0),0)/60],['Suma zleceń dodatkowych',orders.reduce((x,o)=>x+Number(o.netAmount||0),0)]]);st.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};st.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF132734'}};
 const buffer=await wb.xlsx.writeBuffer();return new Response(buffer,{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="raport_safety_service.xlsx"'}})
}
