'use client';
import { useEffect, useMemo, useState } from 'react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';

const modules=[['dashboard','Podsumowanie'],['clients','Klienci'],['employees','Baza pracowników'],['work','Panel pracownika'],['ai','AI analiza rentowności'],['charts','Wykres czasu pracy'],['profitCharts','Wykres rentowności'],['import','Import danych'],['export','Eksporty'],['security','Bezpieczeństwo i konto'],['users','Użytkownicy i role'],['pwa','PWA / telefon']];
const workTypes=['dokumentacja','audyt','szkolenie','dojazd','email','telefon','inne'];
function minToText(m){const h=Math.floor((m||0)/60),mm=(m||0)%60;return `${h}h ${mm}m`}
function money(v){return `${Number(v||0).toLocaleString('pl-PL')} zł`}
function parseTime(s){s=String(s||'').toLowerCase().replace(',','.').trim();if(!s)return 0;if(s.includes(':')){const [h,m]=s.split(':');return Number(h)*60+Number(m||0)}const h=s.match(/(\d+(\.\d+)?)\s*h/),m=s.match(/(\d+)\s*m/);if(h||m)return Math.round(Number(h?.[1]||0)*60+Number(m?.[1]||0));return Math.round(Number(s||0)*60)}
function has(user,key){return user.role==='ADMIN'||user.permissions?.[key]}
async function jsonFetch(url,opts){const r=await fetch(url,opts);let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||'Błąd zapisu');return j}
async function nipLookup(nip){const clean=String(nip||'').replace(/\D/g,'');if(clean.length!==10)return null;const r=await fetch('/api/nip/'+clean,{cache:'no-store'});const j=await r.json();return r.ok&&j?.name?j:null}
async function autofillByNip(formEl){try{const nip=formEl?.elements?.nip?.value;if(!nip)return;const d=await nipLookup(nip);if(!d)return;const hasEmpty=['name','address','contactPerson','phone','email'].some(k=>formEl.elements[k]&&!formEl.elements[k].value);if(!hasEmpty)return;if(!confirm('Znaleziono dane po NIP. Uzupełnić puste pola firmy?'))return;if(formEl.elements.name&&!formEl.elements.name.value)formEl.elements.name.value=d.name||'';if(formEl.elements.address&&!formEl.elements.address.value)formEl.elements.address.value=d.address||'';}catch(e){console.warn(e)}}

export default function Dashboard({user}){
 const [tab,setTab]=useState(user.role==='WORKER'?'work':'dashboard');
 const [data,setData]=useState({companies:[],workEntries:[],users:[]});
 const [selectedCompany,setSelectedCompany]=useState(null);
 const [editUser,setEditUser]=useState(null);
 const [ai,setAi]=useState('');
 const [form,setForm]=useState({date:new Date().toISOString().slice(0,10),companyId:'',type:'dokumentacja',title:'',description:'',time:'',travelTime:'',additionalCost:'',additionalCostDescription:'',orderNumber:''});
 async function load(){const r=await fetch('/api/data',{cache:'no-store'});const j=await r.json();setData(j);setSelectedCompany(prev=>prev?j.companies.find(c=>c.id===prev.id)||prev:j.companies?.[0]||null)}
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>{const rows=data.companies.map(c=>{const entries=data.workEntries.filter(w=>w.companyId===c.id);const minutes=entries.reduce((s,e)=>s+e.minutes,0);const travel=entries.reduce((s,e)=>s+(e.travelMinutes||0),0);const net=Number(c.netAmount||0);const variableCosts=entries.reduce((s,e)=>s+Number(e.additionalCost||0),0);const costs=Number(c.travelCost||0)+Number(c.extraCost||0)+variableCosts;const rate=minutes?(net-costs)/(minutes/60):0;const rent=rate>=250?'Wysoka':rate>=150?'Średnia':minutes?'Niska':'Brak';return {...c,entries,minutes,travel,costs,variableCosts,hours:+(minutes/60).toFixed(2),rate:+rate.toFixed(2),rent}});return{rows,totalMin:rows.reduce((s,r)=>s+r.minutes,0),totalIncome:rows.reduce((s,r)=>s+Number(r.netAmount||0),0),best:rows.filter(r=>r.minutes).sort((a,b)=>b.rate-a.rate)[0],time:[...rows].sort((a,b)=>b.minutes-a.minutes)[0]}},[data]);
 async function saveCompany(e){e.preventDefault();const formEl=e.currentTarget;try{const body=Object.fromEntries(new FormData(formEl).entries());const saved=await jsonFetch('/api/companies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setSelectedCompany(saved);formEl.reset();await load();alert('Firma dodana.')}catch(err){alert(err.message)}}
 async function updateCompany(e){e.preventDefault();const formEl=e.currentTarget;try{const body=Object.fromEntries(new FormData(formEl).entries());const saved=await jsonFetch('/api/companies/'+selectedCompany.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setSelectedCompany(saved);await load();alert('Dane firmy zapisane.')}catch(err){alert(err.message)}}
 async function deleteCompany(c){if(!c)return;if(!confirm(`Czy na pewno usunąć firmę: ${c.name}? Usunięte zostaną też wpisy pracy tej firmy.`))return;try{await jsonFetch('/api/companies/'+c.id,{method:'DELETE'});setSelectedCompany(null);await load();alert('Firma usunięta.')}catch(err){alert(err.message)}}
 async function addWork(){try{if(!form.companyId||!form.title||!form.time)return alert('Uzupełnij firmę, czynność i czas.');await jsonFetch('/api/work',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,minutes:parseTime(form.time),travelMinutes:parseTime(form.travelTime),additionalCost:Number(form.additionalCost||0),additionalCostDescription:form.additionalCostDescription})});setForm({...form,title:'',description:'',time:'',travelTime:'',additionalCost:'',additionalCostDescription:'',orderNumber:''});await load();alert('Dodano wpis pracy.')}catch(err){alert(err.message)}}
 async function runAi(){setAi('Analizuję klientów...');const r=await fetch('/api/ai/analyze');const j=await r.json();setAi(j.analysis)}
 async function addUser(e){e.preventDefault();const formEl=e.currentTarget;try{const body=Object.fromEntries(new FormData(formEl).entries());body.permissions=Object.fromEntries(modules.map(([k])=>[k,!!body['perm_'+k]]));modules.forEach(([k])=>delete body['perm_'+k]);await jsonFetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});formEl.reset();await load();alert('Użytkownik dodany.')}catch(err){alert(err.message)}}
 async function saveUser(e){e.preventDefault();const formEl=e.currentTarget;try{const body=Object.fromEntries(new FormData(formEl).entries());body.permissions=Object.fromEntries(modules.map(([k])=>[k,!!body['perm_'+k]]));modules.forEach(([k])=>delete body['perm_'+k]);await jsonFetch('/api/users/'+editUser.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setEditUser(null);await load();alert('Użytkownik zapisany.')}catch(err){alert(err.message)}}
 async function deleteUser(u){if(!confirm(`Czy na pewno usunąć pracownika: ${u.name}?`))return;try{await jsonFetch('/api/users/'+u.id,{method:'DELETE'});if(editUser?.id===u.id)setEditUser(null);await load();alert('Pracownik usunięty.')}catch(err){alert(err.message)}}
 return <div className="app"><aside className="sidebar"><div style={{textAlign:'right'}}>«</div><div className="side-title">Nawigacja</div><div className="userline">Użytkownik: <b>{user.name}</b></div><div className="userline">Rola: <b>{user.role==='ADMIN'?'Administrator':'Pracownik'}</b></div>{modules.map(([key,label])=>has(user,key)&&<button key={key} className={'navbtn '+(tab===key?'active':'')} onClick={()=>{setTab(key);setEditUser(null)}}>{label}</button>)}<a href="/logout" className="navbtn">Wyloguj</a></aside><main className="main"><header className="top"><img src="/logo.png" className="logo" alt="Safety Service"/><div className="title">ROZLICZANIE OBSŁUGI FIRM ONLINE</div><a className="btn" href="/logout">Wyloguj</a></header><div className="content">
 {tab==='dashboard'&&<div className="panel"><h1>Podsumowanie</h1><div className="kpis"><div className="card">Firmy<div className="kpi">{data.companies.length}</div></div><div className="card">Godziny<div className="kpi">{minToText(stats.totalMin)}</div></div><div className="card">Przychód<div className="kpi">{money(stats.totalIncome)}</div></div><div className="card">Najbardziej rentowny<div className="kpi">{stats.best?.name||'-'}</div></div></div><SummaryTable rows={stats.rows}/></div>}
 {tab==='clients'&&<div className="panel"><div className="grid"><form className="card" onSubmit={saveCompany}><h2>Dodaj firmę</h2><input name="name" placeholder="Nazwa firmy" required/><input name="nip" placeholder="NIP" onBlur={e=>autofillByNip(e.currentTarget.form)}/><input name="address" placeholder="Adres"/><input name="contactPerson" placeholder="Osoba kontaktowa"/><input name="phone" placeholder="Telefon"/><input name="email" placeholder="Email"/><input name="serviceType" placeholder="Typ obsługi"/><select name="assignedUserId"><option value="">Przypisz pracownika</option>{data.users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select name="status"><option value="ACTIVE">aktywna</option><option value="PAUSED">zawieszona</option><option value="INACTIVE">nieaktywna</option></select><select name="billingType"><option value="MONTHLY">miesięczne</option><option value="ONE_TIME">jednorazowe</option><option value="HOURLY">godzinowe</option></select><input name="netAmount" type="number" placeholder="Kwota netto"/><input name="travelCost" type="number" placeholder="Koszt dojazdów"/><input name="extraCost" type="number" placeholder="Dodatkowe koszty"/><button className="orange">Zapisz</button></form><div className="card"><h2>Baza firm</h2><div className="tableWrap"><table><thead><tr><th>Status</th><th>Firma</th><th>NIP</th><th>Pracownik</th><th>Kwota</th></tr></thead><tbody>{data.companies.map(c=><tr className="clickable" key={c.id} onClick={()=>setSelectedCompany(c)}><td><span className={'status '+c.status}></span></td><td>{c.name}</td><td>{c.nip||'-'}</td><td>{c.assignedUser?.name||'-'}</td><td>{money(c.netAmount)}</td></tr>)}</tbody></table></div>{selectedCompany&&<CompanyDetails key={selectedCompany.id} company={selectedCompany} users={data.users} onSubmit={updateCompany} onDelete={()=>deleteCompany(selectedCompany)}/>}</div></div></div>}
 {tab==='employees'&&<div className="panel"><h1>Baza pracowników</h1><div className="grid3">{data.users.map(u=><EmployeeCard key={u.id} u={u} onEdit={()=>{setEditUser(u);setTab('users')}} onDelete={()=>deleteUser(u)}/>)}</div></div>}
 {tab==='work'&&<div className="panel"><div className="card" style={{maxWidth:760}}><h1>Panel pracownika</h1><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><select value={form.companyId} onChange={e=>setForm({...form,companyId:e.target.value})}><option value="">Wybierz firmę</option>{data.companies.filter(c=>c.status!=='INACTIVE').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="Numer zlecenia opcjonalnie" value={form.orderNumber} onChange={e=>setForm({...form,orderNumber:e.target.value})}/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{workTypes.map(t=><option key={t}>{t}</option>)}</select><input placeholder="Czynność" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="Opis wykonanych prac" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="Czas pracy np. 2:30, 2h 30m, 150m" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/><input placeholder="Czas dojazdu np. 30m" value={form.travelTime} onChange={e=>setForm({...form,travelTime:e.target.value})}/><input placeholder="Dodatkowy koszt np. 300" value={form.additionalCost} onChange={e=>setForm({...form,additionalCost:e.target.value})}/><input placeholder="Opis kosztu np. ratownik medyczny" value={form.additionalCostDescription} onChange={e=>setForm({...form,additionalCostDescription:e.target.value})}/><button type="button" className="orange" onClick={addWork}>Dodaj wpis</button></div></div>}
 {tab==='ai'&&<div className="panel"><h1>AI analiza rentowności</h1><button className="orange" onClick={runAi}>Uruchom AI analizę</button><p>{ai||'AI obliczy rentowność każdego klienta i poda konkretne podpowiedzi.'}</p></div>}
 {tab==='charts'&&<ChartPanel title="Wykres czasu pracy" rows={stats.rows.slice().sort((a,b)=>b.hours-a.hours).slice(0,12)} dataKey="hours" color="#ff5a14"/>}
 {tab==='profitCharts'&&<ChartPanel title="Wykres rentowności" rows={stats.rows.filter(r=>r.minutes).sort((a,b)=>b.rate-a.rate).slice(0,12)} dataKey="rate" color="#132734"/>}
 {tab==='import'&&<div className="panel"><h1>Import danych</h1><p>Excel: Nazwa firmy, NIP, Kwota, Uwagi.</p><form action="/api/import/excel" method="post" encType="multipart/form-data"><input type="file" name="file" accept=".xlsx,.csv"/><button className="orange">Import danych</button></form></div>}
 {tab==='export'&&<div className="panel"><h1>Eksporty</h1><div className="row"><a className="btn orange" href="/api/export/excel">Excel miesięczny/roczny</a><a className="btn" href="/api/export/csv">CSV</a><a className="btn" href="/api/export/pdf" target="_blank">PDF</a></div></div>}
 {tab==='security'&&<div className="panel"><h1>Bezpieczeństwo i konto</h1><p>Zalogowano jako: <b>{user.name}</b> ({user.role})</p><h2>Backup systemu</h2><div className="backupBar">Ostatni backup: {new Date().toISOString()} (daily)</div><p><a className="btn red" href="/api/backup">Utwórz backup teraz</a></p><h2>Ostatnie zdarzenia</h2><AuditTable/></div>}
 {tab==='users'&&<UsersPanel data={data} editUser={editUser} setEditUser={setEditUser} addUser={addUser} saveUser={saveUser} deleteUser={deleteUser}/>} 
 {tab==='pwa'&&<div className="panel"><h1>Aplikacja mobilna PWA</h1><p><b>Android:</b> Chrome → trzy kropki → Dodaj do ekranu głównego.</p><p><b>iPhone:</b> Safari → Udostępnij → Do ekranu początkowego.</p></div>}
 </div></main></div>
}
function SummaryTable({rows}){return <div className="card"><h2>Podsumowanie</h2><div className="tableWrap"><table><thead><tr><th>Firma</th><th>Godziny</th><th>Kwota netto</th><th>Koszty dodatkowe</th><th>Stawka/h</th><th>Rentowność</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><span className={'status '+r.status}></span>{r.name}</td><td>{minToText(r.minutes)}</td><td>{money(r.netAmount)}</td><td>{money(r.costs||0)}</td><td>{r.rate.toFixed(2)} zł/h</td><td>{r.rent}</td></tr>)}</tbody></table></div></div>}
function CompanyDetails({company,users,onSubmit,onDelete}){
 const missing=['nip','address','contactPerson','phone','email'].filter(k=>!company[k]);
 useEffect(()=>{let alive=true;(async()=>{if(company.nip&&missing.length){const ok=confirm(`W firmie ${company.name} brakuje danych: ${missing.join(', ')}. Spróbować uzupełnić po NIP?`);if(ok&&alive){const formEl=document.getElementById('companyEditForm');if(formEl) await autofillByNip(formEl)}}})();return()=>{alive=false}},[company.id]);
 return <form id="companyEditForm" className="detailBox" onSubmit={onSubmit}><div className="row between"><h2>Dane firmy: {company.name}</h2><button type="button" className="red" onClick={onDelete}>🗑️ Usuń firmę</button></div>{missing.length>0&&<div className="warnBox">Brakuje danych: {missing.join(', ')}. Wpisz NIP i kliknij pole obok albo użyj przycisku poniżej.</div>}<div className="companyInfo"><div className="infoBox"><b>Kontakt</b>{company.contactPerson||'-'}</div><div className="infoBox"><b>Email</b>{company.email||'-'}</div><div className="infoBox"><b>Telefon</b>{company.phone||'-'}</div><div className="infoBox"><b>Adres</b>{company.address||'-'}</div><div className="infoBox"><b>Pracownik</b>{company.assignedUser?.name||'-'}</div><div className="infoBox"><b>Status</b><span className={'status '+company.status}></span>{company.status}</div></div><div className="grid2"><input name="name" defaultValue={company.name}/><input name="nip" defaultValue={company.nip||''} placeholder="NIP" onBlur={e=>autofillByNip(e.currentTarget.form)}/><input name="address" defaultValue={company.address||''} placeholder="Adres"/><input name="contactPerson" defaultValue={company.contactPerson||''} placeholder="Osoba kontaktowa"/><input name="phone" defaultValue={company.phone||''} placeholder="Telefon"/><input name="email" defaultValue={company.email||''} placeholder="Email"/><input name="serviceType" defaultValue={company.serviceType||''} placeholder="Typ obsługi"/><select name="assignedUserId" defaultValue={company.assignedUserId||''}><option value="">Brak pracownika</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select name="status" defaultValue={company.status}><option value="ACTIVE">aktywna</option><option value="PAUSED">zawieszona</option><option value="INACTIVE">nieaktywna</option></select><select name="billingType" defaultValue={company.billingType}><option value="MONTHLY">miesięczne</option><option value="ONE_TIME">jednorazowe</option><option value="HOURLY">godzinowe</option></select><input name="netAmount" defaultValue={company.netAmount} placeholder="Kwota netto"/><input name="travelCost" defaultValue={company.travelCost} placeholder="Koszt dojazdów"/><input name="extraCost" defaultValue={company.extraCost} placeholder="Dodatkowe koszty"/></div><div className="row"><button type="button" className="light" onClick={e=>autofillByNip(e.currentTarget.form)}>Uzupełnij puste dane z NIP</button><button className="orange">Zapisz zmiany firmy</button></div></form>}
function EmployeeCard({u,onEdit,onDelete}){return <div className="card employeeCard"><div><h2>{u.name}</h2><p>ID: {u.id.slice(0,6)} | Login: {u.email}</p><span className="pill">{u.role==='ADMIN'?'Administrator':'BHP'}</span> <span className="pill green">{u.active?'Aktywny':'Nieaktywny'}</span></div><div className="employeeActions"><button className="light iconBtn" title="Edytuj" onClick={onEdit}>✏️</button><button className="light iconBtn" title="Usuń" onClick={onDelete}>🗑️</button></div></div>}
function UsersPanel({data,editUser,setEditUser,addUser,saveUser,deleteUser}){return <div className="panel">{!editUser&&<><h1>Użytkownicy i role</h1><form className="card" onSubmit={addUser}><h2>Dodaj użytkownika</h2><div className="grid2"><input name="email" placeholder="Login nowego użytkownika" required/><input name="name" placeholder="Imię i nazwisko" required/><input name="password" type="password" placeholder="Hasło tymczasowe" required/><select name="role"><option value="ADMIN">Administrator</option><option value="WORKER">BHP / Pracownik</option></select></div><h3>Uprawnienia</h3><div className="permGrid">{modules.map(([k,l])=><label key={k}><input name={'perm_'+k} type="checkbox" defaultChecked={k==='work'||k==='pwa'}/> {l}</label>)}</div><button>Dodaj użytkownika</button></form><h2>Lista użytkowników</h2>{data.users.map(u=><div className="card employeeCard" key={u.id}><div><h3>{u.name}</h3><p>ID: {u.id.slice(0,6)} | Login: {u.email}</p><span className="pill">{u.role}</span> <span className="pill green">{u.active?'Aktywny':'Nieaktywny'}</span></div><div className="employeeActions"><button className="light iconBtn" onClick={()=>setEditUser(u)}>✏️</button><button className="light iconBtn" onClick={()=>deleteUser(u)}>🗑️</button></div></div>)}</>}{editUser&&<form className="card" onSubmit={saveUser}><h1>✏️ Edycja konta użytkownika</h1><button type="button" className="light" onClick={()=>setEditUser(null)}>← Wróć do listy użytkowników</button><div className="grid2"><input name="email" defaultValue={editUser.email}/><input name="name" defaultValue={editUser.name}/><select name="role" defaultValue={editUser.role}><option value="ADMIN">Administrator</option><option value="WORKER">BHP / Pracownik</option></select><label><input name="active" type="checkbox" defaultChecked={editUser.active} style={{width:'auto'}}/> Konto aktywne</label></div><h2>Uprawnienia</h2><div className="permGrid">{modules.map(([k,l])=><label key={k}><input name={'perm_'+k} type="checkbox" defaultChecked={!!editUser.permissions?.[k]}/> {l}</label>)}</div><input name="password" type="password" placeholder="Nowe hasło — zostaw puste, jeśli nie chcesz zmieniać"/><button>Zapisz zmiany</button> <button type="button" className="red" onClick={()=>deleteUser(editUser)}>Usuń użytkownika</button></form>}</div>}
function ChartPanel({title,rows,dataKey,color}){return <div className="panel"><h1>{title}</h1><div className="card chartBox"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey={dataKey} fill={color}/></BarChart></ResponsiveContainer></div></div>}
function AuditTable(){return <div className="tableWrap"><table><thead><tr><th>id</th><th>event_time</th><th>username</th><th>action</th><th>details</th></tr></thead><tbody><tr><td>1</td><td>{new Date().toISOString()}</td><td>admin</td><td>LOGOWANIE</td><td>Udane logowanie</td></tr></tbody></table></div>}
